name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install UV
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: uv sync
    
    - name: Run basic tests
      run: |
        # Test that agents can be imported and configured
        uv run python -c "from configurable_agent import main"
        uv run python -c "from coordinator_agent import main"
        uv run python -c "from a2a_client import main"
        
        # Test configuration loading
        uv run python -c "
        import tomllib
        from pathlib import Path
        config_path = Path('config/config.toml')
        with open(config_path, 'rb') as f:
            config = tomllib.load(f)
        print('✅ Configuration loads successfully')
        "
    
    - name: Check code style
      run: |
        uv add --dev ruff
        uv run ruff check .
      continue-on-error: true
    
    - name: Security scan
      run: |
        uv add --dev bandit
        uv run bandit -r . -f json -o bandit-report.json
      continue-on-error: true
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.python-version }}
        path: |
          bandit-report.json
          .coverage*
        retention-days: 30 